"""Generate deterministic JSON Schemas and TypeScript declarations from Pydantic."""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
PYTHON_CONTRACTS = ROOT / "shared" / "contracts" / "python"
if str(PYTHON_CONTRACTS) not in sys.path:
    sys.path.insert(0, str(PYTHON_CONTRACTS))

from iprisk_contracts import (  # noqa: E402
    AnalysisArtifact,
    AnalysisResult,
    SourceChange,
    SourceSnapshot,
)

MODELS = {
    "SourceChange": (SourceChange, "source-change.v1.json"),
    "SourceSnapshot": (SourceSnapshot, "source-snapshot.v1.json"),
    "AnalysisArtifact": (AnalysisArtifact, "analysis-artifact.v1.json"),
    "AnalysisResult": (AnalysisResult, "analysis-result.v1.json"),
}


def stable_json(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def ts_literal(value: Any) -> str:
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    return json.dumps(value, ensure_ascii=False)


def ts_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", 1)[-1]
    if "const" in schema:
        return ts_literal(schema["const"])
    if "enum" in schema:
        return " | ".join(ts_literal(value) for value in schema["enum"])
    if "anyOf" in schema:
        return " | ".join(ts_type(option) for option in schema["anyOf"])
    schema_type = schema.get("type")
    if isinstance(schema_type, list):
        return " | ".join(ts_type({"type": item}) for item in schema_type)
    if schema_type == "string":
        return "string"
    if schema_type in {"integer", "number"}:
        return "number"
    if schema_type == "boolean":
        return "boolean"
    if schema_type == "null":
        return "null"
    if schema_type == "array":
        item_type = ts_type(schema.get("items", {}))
        return f"Array<{item_type}>"
    if schema_type == "object":
        properties = schema.get("properties")
        if properties:
            required = set(schema.get("required", []))
            parts = [
                f"{name}{'' if name in required else '?'}: {ts_type(value)};"
                for name, value in sorted(properties.items())
            ]
            return "{ " + " ".join(parts) + " }"
        additional = schema.get("additionalProperties")
        if isinstance(additional, dict):
            return f"{{ [key: string]: {ts_type(additional)} }}"
        return "Record<string, never>"
    return "never"


def render_declaration(name: str, schema: dict[str, Any]) -> str:
    if name == "JsonValue":
        return (
            "export type JsonValue =\n"
            "  | string\n"
            "  | number\n"
            "  | boolean\n"
            "  | null\n"
            "  | JsonValue[]\n"
            "  | { [key: string]: JsonValue };"
        )
    if schema.get("type") == "object" and "properties" in schema:
        required = set(schema.get("required", []))
        lines = [f"export interface {name} {{"]
        for prop_name, prop_schema in sorted(schema["properties"].items()):
            optional = "" if prop_name in required else "?"
            lines.append(f"  {prop_name}{optional}: {ts_type(prop_schema)};")
        lines.append("}")
        return "\n".join(lines)
    return f"export type {name} = {ts_type(schema)};"


def generate() -> None:
    schema_dir = ROOT / "shared" / "contracts" / "schemas"
    generated_dir = ROOT / "shared" / "contracts" / "typescript" / "generated"
    schema_dir.mkdir(parents=True, exist_ok=True)
    generated_dir.mkdir(parents=True, exist_ok=True)

    schemas: dict[str, dict[str, Any]] = {}
    definitions: dict[str, dict[str, Any]] = {}
    for model_name, (model, filename) in MODELS.items():
        schema = model.model_json_schema(mode="validation")
        schemas[model_name] = schema
        (schema_dir / filename).write_text(stable_json(schema), encoding="utf-8", newline="\n")
        for def_name, definition in schema.get("$defs", {}).items():
            existing = definitions.get(def_name)
            if existing is not None and existing != definition:
                raise RuntimeError(f"conflicting JSON Schema definition: {def_name}")
            definitions[def_name] = definition

    declarations = [
        "// Generated by scripts/generate_contracts.py. Do not edit.",
        "",
    ]
    for name in sorted(definitions):
        declarations.extend((render_declaration(name, definitions[name]), ""))
    for name in MODELS:
        root_schema = {key: value for key, value in schemas[name].items() if key != "$defs"}
        declarations.extend((render_declaration(name, root_schema), ""))
    output = "\n".join(declarations).rstrip() + "\n"
    (generated_dir / "contracts.ts").write_text(output, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    generate()

