"""Frozen public API for IP Risk Agent shared contracts version 1."""

from .analysis_artifact import AnalysisArtifact
from .analysis_result import AnalysisResult
from .common import (
    AnalysisCoverage,
    AnalysisSecurityContext,
    AnalysisStatus,
    AnalysisType,
    AnalysisVersions,
    ArtifactKind,
    ChangeType,
    ContentScope,
    Evidence,
    EvidenceType,
    LicenseCandidate,
    LicensePolicyOutcome,
    MountRef,
    OriginalSourceLocator,
    OriginalSourceType,
    PatentCandidate,
    ProviderFailure,
    ReviewPriority,
    SafeMetadata,
    SegmentKind,
    SourceAccessReceipt,
    SourceAccessType,
    SourceArtifactRef,
    SourceHealth,
    SourceHealthStatus,
    SourceType,
    TextSegment,
)
from .source_adapter import ReconcileResult, SourceAdapter
from .source_change import SourceChange
from .source_snapshot import SourceSnapshot

__all__ = [
    "AnalysisArtifact",
    "AnalysisCoverage",
    "AnalysisResult",
    "AnalysisSecurityContext",
    "AnalysisStatus",
    "AnalysisType",
    "AnalysisVersions",
    "ArtifactKind",
    "ChangeType",
    "ContentScope",
    "Evidence",
    "EvidenceType",
    "LicenseCandidate",
    "LicensePolicyOutcome",
    "MountRef",
    "OriginalSourceLocator",
    "OriginalSourceType",
    "PatentCandidate",
    "ProviderFailure",
    "ReconcileResult",
    "ReviewPriority",
    "SafeMetadata",
    "SegmentKind",
    "SourceAccessReceipt",
    "SourceAccessType",
    "SourceAdapter",
    "SourceArtifactRef",
    "SourceChange",
    "SourceHealth",
    "SourceHealthStatus",
    "SourceSnapshot",
    "SourceType",
    "TextSegment",
]
