"""Async repository and Unit of Work protocols owned by the Control Plane."""

from __future__ import annotations

from typing import Protocol

from iprisk_contracts import AnalysisType

from ip_risk_agent.application.analysis_jobs.models import AnalysisJob
from ip_risk_agent.application.process_change.models import ChangeEvent
from ip_risk_agent.core.artifacts import Artifact, ArtifactState
from ip_risk_agent.core.audit import AuditEvent, SourceAccessEvent
from ip_risk_agent.core.auth import User
from ip_risk_agent.core.memberships import Membership, MembershipInvitation
from ip_risk_agent.core.mounts import SourceConnection, SourceWorkspace, WorkspaceMount
from ip_risk_agent.core.notifications import Notification
from ip_risk_agent.core.risk import Risk, RiskEvent, RiskEvidence, RiskLifecycleState
from ip_risk_agent.core.workspaces import RiskWorkspace


class UserRepository(Protocol):
    async def get(self, user_id: str) -> User | None: ...
    async def get_by_google_subject(self, google_subject: str) -> User | None: ...
    async def add(self, user: User) -> None: ...
    async def save(self, user: User) -> None: ...


class WorkspaceRepository(Protocol):
    async def get(self, workspace_id: str) -> RiskWorkspace | None: ...
    async def add(self, workspace: RiskWorkspace) -> None: ...
    async def save(self, workspace: RiskWorkspace) -> None: ...
    async def list_for_user(self, user_id: str) -> tuple[RiskWorkspace, ...]: ...


class MembershipRepository(Protocol):
    async def get(self, risk_workspace_id: str, user_id: str) -> Membership | None: ...
    async def get_invitation(self, invitation_id: str) -> MembershipInvitation | None: ...
    async def add(self, membership: Membership) -> None: ...
    async def save(self, membership: Membership) -> None: ...
    async def add_invitation(self, invitation: MembershipInvitation) -> None: ...
    async def save_invitation(self, invitation: MembershipInvitation) -> None: ...
    async def list_members(self, risk_workspace_id: str) -> tuple[Membership, ...]: ...
    async def list_invitations(
        self, risk_workspace_id: str
    ) -> tuple[MembershipInvitation, ...]: ...
    async def list_invitations_for_email(
        self, email: str
    ) -> tuple[MembershipInvitation, ...]: ...


class SourceMetadataRepository(Protocol):
    async def get_connection(self, connection_id: str) -> SourceConnection | None: ...
    async def add_connection(self, connection: SourceConnection) -> None: ...
    async def save_connection(self, connection: SourceConnection) -> None: ...
    async def get_source_workspace(self, source_workspace_id: str) -> SourceWorkspace | None: ...
    async def add_source_workspace(self, source_workspace: SourceWorkspace) -> None: ...
    async def save_source_workspace(self, source_workspace: SourceWorkspace) -> None: ...


class MountRepository(Protocol):
    async def get(self, mount_id: str) -> WorkspaceMount | None: ...
    async def add(self, mount: WorkspaceMount) -> None: ...
    async def save(self, mount: WorkspaceMount) -> None: ...
    async def remove(self, mount_id: str) -> None: ...
    async def list_for_workspace(self, risk_workspace_id: str) -> tuple[WorkspaceMount, ...]: ...
    async def list_by_custodian(
        self, risk_workspace_id: str, user_id: str
    ) -> tuple[WorkspaceMount, ...]: ...


class ArtifactRepository(Protocol):
    async def get(self, artifact_id: str) -> Artifact | None: ...
    async def get_by_source_identity(
        self, source_workspace_id: str, source_artifact_id: str
    ) -> Artifact | None: ...
    async def add(self, artifact: Artifact, state: ArtifactState) -> None: ...
    async def save(self, artifact: Artifact) -> None: ...
    async def get_state(self, artifact_id: str) -> ArtifactState | None: ...
    async def save_state(self, state: ArtifactState) -> None: ...
    async def list_for_workspace(
        self, risk_workspace_id: str
    ) -> tuple[Artifact, ...]: ...


class ChangeEventRepository(Protocol):
    async def get(self, change_event_id: str) -> ChangeEvent | None: ...
    async def get_by_fingerprint(self, event_fingerprint: str) -> ChangeEvent | None: ...
    async def add(self, event: ChangeEvent) -> None: ...
    async def save(self, event: ChangeEvent) -> None: ...
    async def list_for_workspace(
        self, risk_workspace_id: str
    ) -> tuple[ChangeEvent, ...]: ...
    async def list_for_artifact(self, artifact_id: str) -> tuple[ChangeEvent, ...]: ...


class AnalysisJobRepository(Protocol):
    async def get(self, analysis_job_id: str) -> AnalysisJob | None: ...
    async def add(self, job: AnalysisJob) -> None: ...
    async def save(self, job: AnalysisJob) -> None: ...
    async def list_for_change(self, change_event_id: str) -> tuple[AnalysisJob, ...]: ...


class RiskRepository(Protocol):
    async def get(self, risk_id: str) -> Risk | None: ...
    async def get_by_key(self, risk_key: str) -> Risk | None: ...
    async def add(self, risk: Risk) -> None: ...
    async def save(self, risk: Risk) -> None: ...
    async def list_for_artifact(
        self,
        artifact_id: str,
        analysis_type: AnalysisType,
        lifecycle_states: frozenset[RiskLifecycleState] | None = None,
    ) -> tuple[Risk, ...]: ...
    async def list_for_workspace(self, risk_workspace_id: str) -> tuple[Risk, ...]: ...
    async def add_evidence(self, evidence: RiskEvidence) -> None: ...
    async def list_evidence(
        self, risk_id: str, *, analysis_job_id: str | None = None
    ) -> tuple[RiskEvidence, ...]:
        """근거 행. ``analysis_job_id`` 를 주면 그 실행이 남긴 것만.

        근거는 실행마다 쌓인다 — :meth:`clear_evidence` 가 **같은 실행**의 행만 지우기
        때문이다. 그래야 이력(``RiskEvent.evidence_refs``)이 가리키는 행이 살아 있고,
        "그때 무엇을 보고 그렇게 판단했는가" 를 되짚을 수 있다.

        대신 **지금 판정을 보여 줄 때는 걸러야 한다.** 안 거르면 옛 corpus 판본에서
        나온 조각이 현재 판정 옆에 나란히 서고, 판정에 적힌 ``rag_corpus_version`` 과
        근거가 서로 다른 시점을 가리키게 된다.
        """
        ...
    async def clear_evidence(self, risk_id: str, analysis_job_id: str) -> int: ...
    async def append_event(self, event: RiskEvent) -> None: ...
    async def list_events(self, risk_id: str) -> tuple[RiskEvent, ...]: ...


class AuditRepository(Protocol):
    async def append(self, event: AuditEvent) -> None: ...
    async def list_for_workspace(self, risk_workspace_id: str) -> tuple[AuditEvent, ...]: ...
    async def get_source_access(self, event_id: str) -> SourceAccessEvent | None: ...
    async def append_source_access(self, event: SourceAccessEvent) -> None: ...
    async def list_source_access(
        self, risk_workspace_id: str
    ) -> tuple[SourceAccessEvent, ...]: ...


class NotificationRepository(Protocol):
    async def get(self, notification_id: str) -> Notification | None: ...
    async def add(self, notification: Notification) -> None: ...
    async def save(self, notification: Notification) -> None: ...
    async def list_for_user(self, user_id: str) -> tuple[Notification, ...]: ...


class ControlUnitOfWork(Protocol):
    users: UserRepository
    workspaces: WorkspaceRepository
    memberships: MembershipRepository
    source_metadata: SourceMetadataRepository
    mounts: MountRepository
    artifacts: ArtifactRepository
    change_events: ChangeEventRepository
    analysis_jobs: AnalysisJobRepository
    risks: RiskRepository
    audit: AuditRepository
    notifications: NotificationRepository

    async def __aenter__(self) -> "ControlUnitOfWork": ...
    async def __aexit__(self, exc_type, exc, traceback) -> None: ...
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...


class ControlUnitOfWorkFactory(Protocol):
    def __call__(self) -> ControlUnitOfWork: ...
